name: Telegram Olheiro Bot

on:
  schedule:
    - cron: '0 */6 * * *' # Reinicia a cada 6 horas
  workflow_dispatch:      # Permite iniciar manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # Um pouco menos de 6 horas para evitar erro abrupto
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon python-dotenv requests psutil

      - name: Run Bot
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          ALERT_BOT_TOKEN: ${{ secrets.ALERT_BOT_TOKEN }}
          MY_TELEGRAM_ID: ${{ secrets.MY_TELEGRAM_ID }}
          TELEGRAM_SESSION_BASE64: ${{ secrets.TELEGRAM_SESSION_BASE64 }}
        run: |
          python telegram_channel_monitor.py
